const faker = require('faker');
const { randomUppercase, randomNum } = require('./helpers');

faker.seed(100);

// Data structure.
// {
//   _id: (Generated by MongoDB), (searchMode, searchKey)
//   shipNumber: 'AK-24560-XZ', (searchMode, searchKey)
//   owner: 'Jack Carlo', (searchMode, searchKey)
//   city: 'South Dakota',
//   registerDate: "2020-08-27", (sort)
//   fishType: 'Tuna', (filter)
//   weight: 100, (sort)
// }

let fishTypes = ['Tuna', 'Snappers', 'Cod', 'Anchovy', 'Swordfish'];

let deliveries = [];
let deliveriesAmount = 103;

for (let i = 0; i < deliveriesAmount; i++) {
  deliveries.push({
    shipNumber: generateShipNumber(),
    owner: `${faker.name.firstName()} ${faker.name.lastName()}`,
    city: faker.address.state(false),
    registerDate: faker.date.past(10, new Date()),
    fishType: faker.helpers.randomize(fishTypes),
    weight: faker.random.number(1000),
  });
}

function generateShipNumber() {
  return `${randomUppercase(2)}-${randomNum(1000, 9999)}-${randomUppercase(3)}`;
}

module.exports = deliveries;
